services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    command:
      [
        "/usr/local/bin/redis-server",
        "--maxmemory",
        "150mb",
        "--maxmemory-policy",
        "allkeys-lru",
      ]

  processor:
    image: ghcr.io/smileyniloc/cradlewave-processor:main
    container_name: cradlewave-processor
    restart: unless-stopped
    network_mode: host
    depends_on:
      - redis

  exporter:
    image: ghcr.io/smileyniloc/cradlewave-exporter:main
    container_name: cradlewave-exporter
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/ubuntu/certs/google:/app/certs:ro
    environment:
      - GOOGLE_KEY=/app/certs/cradlewave-aa74f-firebase-adminsdk.json
    ports:
      - "8080:8080"
    depends_on:
      - redis

  ingestor:
    image: ghcr.io/smileyniloc/cradlewave-ingestor:main
    container_name: cradlewave-ingestor
    restart: unless-stopped
    network_mode: host
    depends_on:
      - redis
    volumes:
      - /home/ubuntu/certs/amazon:/app/certs:ro
    environment:
      - AWS_ROOT_CA=/app/certs/root-CA.crt
      - AWS_PRIVATE_KEY=/app/certs/oracle-vm.private.key
      - AWS_CERT=/app/certs/oracle-vm.cert.pem
