services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  processor:
    build:
      context: ../webdev/backend/processor
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
