services:
  backend:
    image: python:3.11-slim
    container_name: backend
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 3047 --reload"
    volumes:
      - ./backend/:/app
    ports:
      - "3047:3047"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: node:20-alpine
    working_dir: /app
    container_name: frontend
    command: sh -c "npm install && npm run serve -- --host 0.0.0.0 --port 80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5047:80"
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
