services:
  backend:
    build: ./backend
    container_name: backend
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./backend/:/app
    ports:
      - "3047:80"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    image: node:20-alpine
    working_dir: /app
    container_name: frontend
    command: sh -c "npm install && npm run serve -- --host 0.0.0.0 --port 80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5047:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

networks:
  app-network:
