name: Push Frontend server to Firebase

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cahce: npm
    - name: Install Dependencies
      working-directory: ./webdev/frontend
      run: npm ci
    - name: Build Project
      working-directory: ./webdev/frontend
      run: npm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: webdev/frontend/dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      # - name: Download build artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: dist-files
      #     path: ./dist
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: 'cradlewave-aa74f'
          entryPoint: ./webdev
